In [1]:
import pandas as pd
import numpy as np

In [2]:
X_train = pd.read_csv('/root/Desktop/Research Set/X_train.csv', sep= ' ', header=None)
X_test = pd.read_csv('/root/Desktop/Research Set/X_test.csv', sep= ' ', header=None)

In [3]:
y_train = pd.read_csv('/root/Desktop/Research Set/y_train.csv', header=None)
y_test = pd.read_csv('/root/Desktop/Research Set/y_test.csv', header=None)

In [4]:
#Converting into numpy array
X_train = X_train.values #last index column is not included

In [5]:
X_train

array([[ 0.04357967, -0.00597022, -0.03505434, ..., -0.84155851,
         0.17991281, -0.05171842],
       [ 0.03948004, -0.00213128, -0.02906736, ..., -0.8450924 ,
         0.18026111, -0.04743634],
       [ 0.03997778, -0.00515272, -0.02265071, ..., -0.84923013,
         0.18060956, -0.04227136],
       ..., 
       [ 0.03745094, -0.00272442,  0.02100941, ..., -0.77956634,
         0.24912145,  0.04707077],
       [ 0.04401105, -0.00453578, -0.0512422 , ..., -0.78560327,
         0.24640867,  0.03170003],
       [ 0.06895376,  0.00181032, -0.08032343, ..., -0.78369253,
         0.24678499,  0.04298129]])

In [6]:
X_test = X_test.values

In [15]:
y_train.head(5)

0
0  5
1  5
2  5
3  5
4  5

In [19]:
from sklearn.preprocessing import OneHotEncoder
onehotencoder = OneHotEncoder()
y_train = onehotencoder.fit_transform(y_train).toarray()

In [20]:
y_train

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  1.,  0., ...,  0.,  0.,  0.],
       [ 0.,  1.,  0., ...,  0.,  0.,  0.],
       [ 0.,  1.,  0., ...,  0.,  0.,  0.]])

In [22]:
#Making the Artificial Neural Network
import keras

Using TensorFlow backend.


In [23]:
#Importing Modules, sequential module is required to initialise the neural network
#and dense module is used to build the layers
from keras.models import Sequential
from keras.layers import Dense

In [24]:
#Importing the Dropout Layer in order to prevent Regularization in the network
from keras.layers import Dropout

In [25]:
#Initialising the deep learning model
#Defining the model as a sequence of layers
classifier = Sequential()

In [26]:
#Adding the consecutive layers, first parameter tells the number of nodes in the layer which is to be added
#second parameter is related to initialization of synaptic weights, 3rd is tha activation function 
#fourth is the number of input dimensions
classifier.add(Dense(output_dim = 128, init='uniform', activation='relu', input_dim = 561))

In [100]:
#Adding more layers
classifier.add(Dropout(p = 0.1))
classifier.add(Dense(output_dim = 64, init='uniform', activation='relu'))
classifier.add(Dropout(p = 0.1))
classifier.add(Dense(output_dim = 32, init='uniform', activation='relu'))
classifier.add(Dropout(p = 0.1))
#Adding the final output layer
#softmax is the activation function used for more than 2 classes 
classifier.add(Dense(output_dim = 12, init='uniform', activation='softmax'))

In [101]:
#Compiling the Artificial Neural Network
#adam is used for Stochastic Gradient Descent
#Since the activation layer is sigmoid in nature for the output layer, the loss is logarithmic loss
#which is of 2 types: 'binary_crossentropy'(for binary) & 'categorical_crossentropy'(for multiclass)
classifier.compile(optimizer='adam', loss='categorical_crossentropy', metrics = ['accuracy'])

In [102]:
#Fitting the ANN to the training set
classifier.fit(X_train, y_train, batch_size=20, nb_epoch=15, verbose = 3)

Epoch 1/15
Epoch 2/15
Epoch 3/15
Epoch 4/15
Epoch 5/15
Epoch 6/15
Epoch 7/15
Epoch 8/15
Epoch 9/15
Epoch 10/15
Epoch 11/15
Epoch 12/15
Epoch 13/15
Epoch 14/15
Epoch 15/15


In [103]:
pred = classifier.predict(X_test)

In [68]:
pred[0]

array([  3.76742741e-04,   2.73522572e-03,   6.42679952e-05,
         9.67095606e-03,   9.84730184e-01,   2.30573892e-06,
         2.04471988e-03,   2.23282434e-04,   4.64436343e-05,
         2.50509629e-06,   1.01733938e-04,   1.69838222e-06], dtype=float32)

In [104]:
predictions = []
for i in range(len(pred)):
    predictions.append(pred[i].argmax() + 1)

In [105]:
from sklearn import metrics
print metrics.accuracy_score(y_test, predictions)

0.925679949399
